[signing]
active = "ALWAYS"
armored = true

[deploy.maven.nexus2.maven-central]
active = "ALWAYS"
url = "https://s01.oss.sonatype.org/service/local"
snapshotUrl = "https://s01.oss.sonatype.org/content/repositories/snapshots/"
stagingRepositories = ["target/staging-deploy"]
closeRepository = true
releaseRepository = true

[release.github]
enabled = true
owner = "OpenElements"
name = "hedera-enterprise"
